stratis-storage/devicemapper-rs

- src/lineardev.rs
- src/thindev.rs
- src/thinpooldev.rs
Add dstr() methods for linear, thinpool, and thin devs.
Use dstr() in dm_table methods for thinpooldev and thindev.
fixes #19
> Use dstr() in dm strings for thinpool and thin devs

- src/thinpooldev.rs
Add a method that gets the DM status for the thinpool, and parses the
textual output. This code is lifted with minor modifications from Froyo.
> Add ThinPoolDev::status()

- src/thindev.rs
Similar to ThinPoolDev::status(), this reads the thin device's status and
converts it from the kernel's text format into proper types.
> Add ThinDev::status()

- Cargo.toml
- src/types.rs
Just needed to add some lifetime annotations to Deserialize impls.
> Update to serde 1.0

- src/thindev.rs
Add a function to ThinDev to return the size.
> Add a size function to thindev.

- Cargo.toml
- src/device.rs
- src/lib.rs
- src/lineardev.rs
- src/segment.rs
If a Segment's fields are going to be all public, these methods are not
appropriate.
> Remove some unneeded methods from Segment

- src/lineardev.rs
- src/result.rs
- src/thinpooldev.rs
See https://github.com/stratis-storage/stratisd/pull/359, these are some dm-rs changes needed for that to work.
> Make repair work

- .travis.yml
> Omit extra space

- .travis.yml
Travis recommends that we do this before tomorrow:
https://blog.travis-ci.com/2017-06-19-trusty-updates-2017-Q2.
> Add group: edge to .travis.yml

- src/util.rs
> Document align_to() method

- src/util.rs
> Simplify slice_to_null

- src/lineardev.rs
It reduces my confusion when reading the code.
> Substitute a more correct word for block.*dev

- .gitignore
Because they should never be commited or searched by rg.
> Ignore backup files from running "cargo fmt"

- Makefile
- src/dm.rs
This extends the existing DM test and add some related header docs and small code changes.
> Extend real tests, those that require sudo

- .travis.yml
Will revert once clippy issues are resolved.
> Allow "clippy" failures

- src/dm.rs
Now that I'm pretty sure that I'll need to use ```device_status()``` to determine if a device of a given name already exists, I think I can move on to working on other problems.
> Miscellaneous changes

- src/dm.rs
- src/thinpooldev.rs
> Use Sectors for argument in target_msg() method

- src/lineardev.rs
- src/thindev.rs
- src/thinpooldev.rs
These commits were all cherry-picked from #110.
> Some comment fixes cherry picked from another PR

- src/types.rs
> Add division by self to the operations available

- rustfmt.toml
- src/dm.rs
- src/lineardev.rs
- src/loopbacked.rs
- src/shared.rs
- src/thindev.rs
- src/thinpooldev.rs
- src/types.rs
This commit also adds a rustfmt.toml to enforce the usage of `?`.
Similar to https://github.com/stratis-storage/stratisd/pull/510
> Convert all `try!` to use `?` operator

- src/dm.rs
- src/lineardev.rs
> Fix some clippy errors

- src/device.rs
- src/lineardev.rs
- src/thinpooldev.rs
These are mostly additional header comments along with a few minor code adjustments for greater clarity.
> Non-semantic changes

- src/dm.rs
- src/thindev.rs
- src/thinpooldev.rs
These are all pulled from #110 .
> Non-controversial cherry-picks

- src/thinpooldev.rs
These are cherry-picked from #110, and essentially unrelated to its main purpose.
> Two minor changes

- src/thinpooldev.rs
"thin_check" fails if the meta data device is "busy"; we believe that it is
certainly "busy" if the kernel knows about it.
> Conditionally run thin_check on thin pool meta data device

- src/thindev.rs
- src/thinpooldev.rs
- src/types.rs
> Add some tests and fix a bug in ThinDev::status()

- src/lineardev.rs
- src/thinpooldev.rs
> Expand the role of LinearDev::new

- src/consts.rs
- src/deviceinfo.rs
- src/dm.rs
- src/lineardev.rs
- src/segment.rs
- src/thindev.rs
- src/thinpooldev.rs
Do any alphabetizing necessary.
> Bring internal use directives into correspondence with style doc

- src/thindev.rs
They have strongly distinguished roles and neither should be implemented in
terms of the other.
> Change semantics of ThinDev::new and ThinDev::setup

- Cargo.toml
> Version 0.9.0

- src/deviceinfo.rs
- src/dm.rs
- src/lineardev.rs
- src/thindev.rs
- src/thinpooldev.rs
- src/types.rs
Partially cherry-picked from #163.
> Miscellaneous small implementations

- src/lib.rs
- src/lineardev.rs
- src/result.rs
- src/shared.rs
- src/thindev.rs
- src/thinpooldev.rs
This PR contains refactorings in ThinDev and LinearDev and significant semantic changes in ThinPoolDev.
> Work on setup in various devices

- src/dm.rs
- src/lineardev.rs
- src/thindev.rs
- src/thinpooldev.rs
> Remove wait_for_dm calls

- src/lineardev.rs
- src/thinpooldev.rs
See stratisd issue https://github.com/stratis-storage/stratisd/issues/550 for motivation.
> Change *extend methods to *reset methods

- Cargo.toml
- src/dm.rs
- src/errors.rs
- src/lib.rs
- src/result.rs
> Introduce error_chain error infrastructure

- src/thinpooldev.rs
> Add a test for data_block_size outside required bounds

- src/cachedev.rs
- src/lib.rs
- src/thinpooldev.rs
It's another type of device that we would like to support.
> Add CacheDev

- Cargo.toml
- src/loopbacked.rs
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
> bump loopdev to 0.2

- src/thindev.rs
For completeness sake and in order to eliminate future bugs.
> Add optional external_origin_dev to TargetParams

- src/dm.rs
- src/shared.rs
- src/shared_macros.rs
The precise error is empty_line_after_outer_attr
> Alter some comments to avoid clippy error

- src/cachedev.rs
- src/lib.rs
For convenience in doing further tests.
> Establish a separate minimal_cachedev() method for testing

- src/thindev.rs
> Change ThinDev::snapshot to take an optional uuid

- src/cachedev.rs
> Specify writethrough feature argument

- src/cachedev.rs
Include a very perfunctory test.
> Add a set_cache_table method to CacheDev

- Cargo.toml
> version 0.18.0

- src/dm.rs
Hopefully bitflags maintainers will address these.
> Allow some clippy errors caused by bitflags! macro

- src/cachedev.rs
- src/lineardev.rs
- src/shared.rs
- src/thindev.rs
- src/thinpooldev.rs
> Change name "load_table" to "read_kernel_table"

- src/thindev.rs
> Give ThinDev a set_table() method

- src/types.rs
> Remove import of AsciiExt

- src/cachedev.rs
- src/lineardev.rs
- src/shared.rs
- src/thindev.rs
- src/thinpooldev.rs
It's nice to be able to view them in a human readable form.
> Implement Display for TargetTables

- src/deviceinfo.rs
- src/dm.rs
- src/types.rs
> Fix clippy errors

- Cargo.toml
- src/lib.rs
- src/loopbacked.rs
- src/thindev.rs
> Use tempfile crate

- Cargo.toml
- Makefile
- src/errors.rs
- src/lib.rs
> Use clippy command

- src/loopbacked.rs
> Use nix::fcntl::fallocate

- Cargo.toml
> version 0.20.1

- Cargo.toml
Since there are API changes, we need to call this 0.21.0.
> version 0.21.0

- .travis.yml
> Build against oldest compiler we support

- src/loopbacked.rs
Previously `get_devices` was creating a sparse file by opening the file,
seeking and writing to the end.  Then it was converted to using `fallocate`
which was creating a non-sparse file.  Fallocate can make an existing file
sparse or add to an existing file as sparse, but for simplying creating
a sparse file to start with `ftruncate` is the simplest approach.
> Fix enospc when testing on system  with small tmpfs

- src/test_lib.rs
- src/thindev.rs
Addresses https://github.com/stratis-storage/devicemapper-rs/issues/256
> Collect stdout & stderr from Command

- src/test_lib.rs
> Fix build error

- src/device.rs
- src/types.rs
These are good suggestions but they are also API changes.
> fixes for latest clippy

- Cargo.toml
> version 0.22.0

- src/dm.rs
- src/dm_ioctl.rs
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
> complete c_char → u8 transition (Struct_dm_target_spec)

- Cargo.toml
- src/dm.rs
- src/loopbacked.rs
Fixes: https://github.com/stratis-storage/devicemapper-rs/issues/348
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
> deps: update nix to 0.11

- Makefile
- src/cachedev.rs
- src/lib.rs
- src/lineardev.rs
- src/shared_macros.rs
- src/test_lib.rs
- src/thindev.rs
- src/thinpooldev.rs
The older version isn't available w/out some effort on Fedora 27.
> Update to newer version of rustfmt

- Cargo.toml
- src/lib.rs
- src/test_lib.rs
Addresses: https://github.com/stratis-storage/devicemapper-rs/issues/342
> Replace mnt-rs with libmount

- src/cachedev.rs
Add a perfunctory test as well.
> Add a function to set the table for the cache meta device

- src/thinpooldev.rs
> Add ThinPoolDev::set_low_water_mark() #2

- Cargo.toml
> version 0.23.0

- .travis.yml
- src/dm.rs
> Build with rustc 1.25

- Cargo.toml
> version 0.23.1

- src/thindev.rs
> Test that ThinDev::destroy() removes the thin_id from use

- src/types.rs
It would have been useful to have it for a test in stratisd.
> Add Sectors % Sectors

- Cargo.toml
> version 0.24.0

- Cargo.toml
> version 0.25.0

- Cargo.toml
> version 0.26.0

- .travis.yml
- Makefile
- src/dm.rs
> Use clippy in the now recommended way

- src/dm.rs
When a vector is resized via v.resize() - the memory location on the
heap may change.  Always update our hdr pointer after a v.resize().
> Update hdr pointer when the memory for the ioctl has been resized

- src/cachedev.rs
- src/lineardev.rs
- src/shared.rs
- src/thindev.rs
- src/thindevid.rs
- src/thinpooldev.rs
Final PR based on work PR #384.
Resolves: #221.
> Parse value final

- Cargo.toml
Updating this crate to 0.7 since the new release is out. There are no further changes required.
> update uuid to 0.7

- Cargo.toml
> version 0.26.1

- src/dm.rs
> Fix unnecessary null return clippy errors

- .travis.yml
- Makefile
It seems we can use just clippy, according to clippy docs.
> Run clippy in newest recommended way

- .travis.yml
> Make lowest supported version 1.31.0

- Makefile
- src/cachedev.rs
- src/device.rs
- src/dm.rs
- src/lineardev.rs
- src/shared.rs
- src/test_lib.rs
- src/thindev.rs
- src/thinpooldev.rs
https://github.com/stratis-storage/stratisd/pull/1381
> Use rustfmt 1.0

- src/lineardev.rs
The error is into-iter-on-ref.
> Fix a clippy lint

- .mergify.yml
Otherwise it doesn't match exactly.
> Add pr to the end of the travis task

- .travis.yml
I keep accidentally fixing it in unrelated PRs, so I'ld like to get rid
of it.
> Remove a trailing space

- Cargo.toml
> Update nix requirement to 0.13

- src/range_macros.rs
- src/types.rs
For completeness and to remove unnecessary code duplication. Test it, too.
> Add implementation of Display to range! macro

- src/cachedev.rs
- src/thindev.rs
- src/thinpooldev.rs
> Parse "Error" value from status

- Cargo.toml
> version 0.27.0

- src/core/device.rs
> Use the correct argument as an argument to format string

- .travis.yml
- Makefile
* Upgrade development compiler to 1.33
* Group Travis tasks into distinct sets with related features and comment
* Add a docs test. Such a test already exists for stratisd, might as well have one here.
> Upgrade recommended development compiler to 1.33

- tests/ci/dm_test.sh
Add script for use with CI that and invokes sudo_test make target
Requires WORKSPACE to bet set to the top level directory.
> Move CI scripts out of Jenkins and into the git repo

- Cargo.toml
> version 0.28.0

- src/lineardev.rs
Addresses the flakey part of #484.
> Properly handle lack of flakey feature args

- src/lineardev.rs
> Implemented flakey target optional feature parameters as an enum

- Makefile
Related: https://github.com/stratis-storage/project/issues/43.
> Add a target to compile but not run tests

- src/thinpooldev.rs
Addresses the thinpool part of #484.
> Properly handle lack of thinpool feature args

- Cargo.toml
- src/testing/test_lib.rs
Related: https://github.com/stratis-storage/project/issues/57.
> Require error-chain 0.12.1

- .travis.yml
Related: https://github.com/stratis-storage/project/issues/96.
> Increase recommended development toolchain to 1.38

- Makefile
- src/cachedev.rs
- src/core/dm.rs
- src/lineardev.rs
- src/shared.rs
- src/thindev.rs
Related: https://github.com/stratis-storage/project/issues/97.
> Disallow clippy needless_borrow

- .travis.yml
- Makefile
Related: https://github.com/stratis-storage/ci/issues/38.
> Remove the sudo commands in sudo-test Makefile target

- src/range_macros.rs
- src/units.rs
> Fix autogenerated docs

- src/cachedev.rs
- src/thinpooldev.rs
Related: https://github.com/stratis-storage/project/issues/106.
> Fix clippy beta 1.40 warnings for deref and redundant clone

- .travis.yml
Related: https://github.com/stratis-storage/project/issues/109.
> Increase recommended development toolchain to 1.39

- src/core/dm.rs
- src/testing/test_lib.rs
Supersedes #516.
Addresses #465.
> Add list_test_devices method

- src/lineardev.rs
> Remove tabs in doc comments

- .travis.yml
Related: https://github.com/stratis-storage/stratisd/pull/1763.
> Do not make beta task an allowed failure

- src/cachedev.rs
- src/core/dm.rs
- src/id_macros.rs
- src/thindev.rs
- src/thinpooldev.rs
> Remove unnecessary clippy allows for new_ret_no_self

- .travis.yml
> Modify Travis configuration file to give each task a name

- .travis.yml
- src/testing/test_lib.rs
Related: https://github.com/stratis-storage/project/issues/139.
> Make beta task mandatory again

- .travis.yml
Related: https://github.com/stratis-storage/project/issues/145.
> Increase recommended development toolchain to 1.41

- src/core/device.rs
- src/thindev.rs
Related: https://github.com/stratis-storage/project/issues/154.
> Remove unnecessary pub modifier on tests

- .travis.yml
- src/core/errors.rs
- src/testing/loopbacked.rs
- src/testing/test_lib.rs
- src/thindev.rs
- src/thindevid.rs
- src/units.rs
Related: https://github.com/stratis-storage/project/issues/155
> beta clippy: remove redundant imports

- .travis.yml
Related: stratis-storage/project#159
> Increase recommended development toolchain to 1.42

- Cargo.toml
- src/testing/test_lib.rs
Related: https://github.com/stratis-storage/project/issues/156
> Require error-chain 0.12.2

- .travis.yml
Related: stratis-storage/project#174
> Increase recommended development toolchain to 1.43

- .travis.yml
Related: stratis-storage/project#188
> Increase recommended development toolchain to 1.44.1

- src/core/dm.rs
Closes #560 
@alexminder Feel free to take a look and test this out if you have the time.
> Fix issue of devicemapper-rs compatibility with musl

- src/thindev.rs
> Just remove troublesome suspend/resume testing in test_basic

- .travis.yml
Related: stratis-storage/project#193
> Increase recommended development toolchain to 1.45.0

- src/thindev.rs
Related: stratis-storage/project#210
> Fix clippy errors for Rust beta 1.47

- .travis.yml
Related: stratis-storage/project#210
> Increase recommended development toolchain to 1.46.0

- .travis.yml
- src/core/dm.rs
Related: stratis-storage/project#210
> parse_table_status: add same_item_push clippy allow

- src/core/dm.rs
Closes https://github.com/stratis-storage/project/issues/223
> Drop a now unnecessary clippy allow

- .travis.yml
Related: stratis-storage/project#230
> Increase recommended development toolchain to 1.47.0

- Cargo.toml
> Upgrade error-chain to 0.12.4

- CHANGES.txt
- Cargo.toml
> version 0.28.1

- README.md
> Get rid of badges in the README

- .github/workflows/main.yml
Related: https://github.com/stratis-storage/project/issues/241
> Increase recommended development toolchain to 1.48.0

- .github/workflows/main.yml
Related: stratis-storage/project#240
> github actions: update lowest supported Rust to 1.47

- src/core/dm.rs
- src/shared.rs
- src/thindev.rs
- src/thindevid.rs
Supersedes: #596 
Related: stratis-storage/project#252
> Resolve Rust 1.49 clippy failures

- src/thinpooldev.rs
Related https://github.com/stratis-storage/stratisd/issues/1495
> Change MAX_RECOMMENDED_METADATA_SIZE to MAX_METADATA_SIZE

- .github/workflows/main.yml
- src/thindev.rs
Related: stratis-storage/project#266
> Increase recommended development version to 1.50.0

- .github/workflows/main.yml
- Cargo.toml
- Makefile
> Deny cargo clippy lints

- .github/workflows/main.yml
- Makefile
- src/shared.rs
- src/thindev.rs
- src/thindevid.rs
Related: stratis-storage/project#276
> Update Rust lints for 1.51

- CHANGES.txt
- Cargo.toml
> version 0.29.1

- src/core/dm.rs
> Remove clippy allows for cast_ptr_alignment

- src/range_macros.rs
> Make all ranges hashable

- Cargo.toml
Related https://github.com/stratis-storage/project/issues/285
> Required version bumps

- .github/workflows/main.yml
- .github/workflows/nightly.yml
- Makefile
Supersedes: #630 
Related: stratis-storage/project#307
> Add compare-fedora-versions tests

- .github/workflows/main.yml
- .github/workflows/nightly.yml
- Makefile
Related https://github.com/stratis-storage/project/issues/307
> Use --manifest-path in Makefiled and CI

- src/cachedev.rs
- src/core/dm_ioctl.rs
- src/thinpooldev.rs
Related https://github.com/stratis-storage/project/issues/315
Supersedes: #638
> Rust 1.53 clippy updates

- Makefile
Related https://github.com/stratis-storage/project/issues/285
> Make verify-dependency-bounds target truly relocatable

- .github/workflows/main.yml
- src/core/deviceinfo.rs
- src/core/util.rs
> Add CI build for Android target

- .github/workflows/nightly.yml
- Makefile
Closes https://github.com/stratis-storage/project/issues/15
> Add a coverage task using tarpaulin to nightly

- .github/workflows/main.yml
- Makefile
Related https://github.com/stratis-storage/project/issues/324
> Combine Fedora dependency checks into one task

- src/core/deviceinfo.rs
- src/core/dm.rs
- src/shared_macros.rs
> Make devicemapper name optional to handle cases where no device is being operated on

- src/id_macros.rs
Related https://github.com/stratis-storage/project/issues/337
> Fix clippy error

- .github/workflows/cargo.yml
- .github/workflows/main.yml
- .github/workflows/nightly.yml
- src/core/device.rs
- src/core/dm.rs
- src/core/errors.rs
- src/thindev.rs
- src/thinpooldev.rs
Related: stratis-storage/project#337
Related: stratis-storage/project#321
> github actions: update recommended Rust to 1.54

- src/core/dm.rs
- src/core/dm_flags.rs
> Use constant values defined in dm-ioctl.h

- devicemapper-rs-sys/Cargo.toml
Related to stratis-storage/project#350
> Devicemapper sys v0.1.1

- src/core/deviceinfo.rs
- src/lineardev.rs
Related: stratis-storage/project#368
> Fix Rust 1.57 clippy errors

- src/core/errors.rs
- src/lib.rs
> Make internal errors module public

- src/cachedev.rs
- src/testing/test_lib.rs
Related: stratis-storage/project#386
> Remove superfluous to_string() calls

- src/core/dm.rs
> Eliminate some expect invocations

- src/thinpooldev.rs
Related to stratis-storage/stratisd#2814
> Default to thin pool queueing and allow changing behavior

- Cargo.toml
- devicemapper-rs-sys/Cargo.toml
Related https://github.com/stratis-storage/project/issues/392
> Increase nix dependency version to 0.23.0

- src/range_macros.rs
Related https://github.com/stratis-storage/project/issues/425
> Fix non-minimal bool lint

- src/lib.rs
- src/shared.rs
Closes https://github.com/stratis-storage/devicemapper-rs/issues/747
> Expose TargetTable and TargetParams

- .github/workflows/cargo.yml
- .github/workflows/nightly.yml
Related https://github.com/stratis-storage/project/issues/377
> Increase lower release to f35 for check-fedora-versions

- .github/workflows/cargo.yml
- .github/workflows/main.yml
- .github/workflows/nightly.yml
Related: stratis-storage/project#464
> github actions: update recommended Rust to 1.61

- Cargo.toml
- devicemapper-rs-sys/Cargo.toml
Related: https://github.com/stratis-storage/project/issues/467
> Increase nix dependency version to 0.24.0

- Cargo.toml
Related https://github.com/stratis-storage/project/issues/470
> Increase uuid dependency version to 1.0.0

- Makefile
Related https://github.com/stratis-storage/project/issues/335
> Require Rust 2021 compatibility lints

- CHANGES.txt
- Cargo.toml
> Version 0.32.1

- Makefile
Related https://github.com/stratis-storage/project/issues/506
> Ignore RUSTSEC-2021-0139 in audit task

- Cargo.toml
- Makefile
- src/core/deviceinfo.rs
- src/core/dm.rs
- src/testing/loopbacked.rs
Related https://github.com/stratis-storage/project/issues/335
> Update to edition 2021

- .github/workflows/cargo.yml
- .github/workflows/nightly.yml
- Cargo.toml
Related https://github.com/stratis-storage/project/issues/507
> Increase loopdev dependency requirement

- CHANGES.txt
- Cargo.toml
Related https://github.com/stratis-storage/project/issues/507
> Version 0.32.2

- devicemapper-rs-sys/Cargo.toml
Related https://github.com/stratis-storage/project/issues/335
> Specify edition 2021 for -sys library

- src/lineardev.rs
- src/testing/test_lib.rs
Related: https://github.com/stratis-storage/project/issues/545
> Fix clippy 1.65 lint errors

- devicemapper-rs-sys/Cargo.toml
Related: stratis-storage/project#551
> Set bindgen dependency to 0.63.0

- src/core/dm.rs
- src/testing/loopbacked.rs
Related: https://github.com/stratis-storage/project/issues/561
> Resolve clippy 1.66 errors

- Cargo.toml
- src/lib.rs
- src/lineardev.rs
Related https://github.com/stratis-storage/project/issues/221
> Use assert_matches instead of matches crate

- Cargo.toml
- src/thindev.rs
Related https://github.com/stratis-storage/project/issues/548
> Remove dev dependency on libudev

- .github/workflows/cargo.yml
- .github/workflows/main.yml
- .github/workflows/nightly.yml
Related: stratis-storage/project#561
> github actions: update recommended Rust to 1.66

- build.rs
- src/cachedev.rs
- src/core/device.rs
- src/core/errors.rs
- src/core/types.rs
- src/lineardev.rs
- src/result.rs
- src/shared.rs
- src/testing/test_lib.rs
- src/thindev.rs
- src/thindevid.rs
- src/thinpooldev.rs
Related: stratis-storage/project#572
> Resolve clippy 1.67 errors

- devicemapper-rs-sys/Cargo.toml
Related https://github.com/stratis-storage/project/issues/569
> devicemapper-sys v0.1.4

- CHANGES.txt
- Cargo.toml
> Version 0.33.0

- CHANGES.txt
- Cargo.toml
Related https://github.com/stratis-storage/project/issues/590
> Version 0.33.2

- CHANGES.txt
- Cargo.toml
Related https://github.com/stratis-storage/project/issues/601
> Version 0.33.3

- Cargo.toml
Related https://github.com/stratis-storage/project/issues/607
> Patch Cargo.toml to avoid loopdev FTBFS

- src/core/dm.rs
Related: stratis-storage/project#619
> Remove unnecessary allocations

- src/core/dm_udev_sync.rs
Test whether the udev daemon appears to be running (by checking the udevd control socket path at /run/udev/control) and refuse to create devices if it is missing.
This change causes stratisd or stratisd-min to exit immediately and log the fact that udev is not running:
```
[2023-05-26T15:45:02Z ERROR stratisd::stratis::run] The devicemapper thread exited with an error: DM error: DM Core error: failed to perform udev sync operation: Udev daemon is not running: unable to create devices.; shutting down stratisd...
Error: "DM error: DM Core error: failed to perform udev sync operation: Udev daemon is not running: unable to create devices."
```
```
× stratisd.service - Stratis daemon
Loaded: loaded (/usr/lib/systemd/system/stratisd.service; enabled; preset: enabled)
Drop-In: …
```
> Test for presence of udev daemon and prevent stratisd-min from starting if it is absent

- .github/workflows/cargo.yml
- .github/workflows/main.yml
- .github/workflows/nightly.yml
Related: stratis-storage/project#628
> github actions: update recommended Rust to 1.71.0

- src/range_macros.rs
Related: stratis-storage/project#655
> Fix useless-vec lint

- .github/workflows/nightly.yml
- Makefile
Related https://github.com/stratis-storage/project/issues/451
> Makefile tidies

- Cargo.toml
Related https://github.com/stratis-storage/project/issues/662
> Use updated branch for loopdev patch entry

- .githooks/pre-commit
- .github/workflows/main.yml
- Makefile
- src/core/dm.rs
- src/core/dm_udev_sync.rs
- src/thindev.rs
- src/thinpooldev.rs
Related: stratis-storage/project#663
> Add typos target to Makefile

- devicemapper-rs-sys/Cargo.toml
Related: stratis-storage/project#662
> Set bindgen dependency to 0.68.1

- src/core/device.rs
Related: stratis-storage/project#671
> Remove redundant guard

- Cargo.toml
- src/testing/loopbacked.rs
Related https://github.com/stratis-storage/project/issues/672
> Increase nix dependency lower bound to 0.27.1

- Cargo.toml
Related https://github.com/stratis-storage/project/issues/677
> Use loopdev-3 instead of loopdev package

- CHANGES.txt
- Cargo.toml
Related https://github.com/stratis-storage/project/issues/677
> devicemapper v0.34.1

- src/core/dm.rs
Related: stratis-storage/project#687
> device_remove: allow blocks in conditions

- .github/workflows/cargo.yml
- .github/workflows/main.yml
- .github/workflows/nightly.yml
- src/core/dm.rs
Related: stratis-storage/project#687
> github actions: update recommended Rust to 1.76.0

- src/testing/loopbacked.rs
- src/thindev.rs
Related: stratis-storage/project#697
> Use explicit OpenOptions::truncate()

- CHANGES.txt
- Cargo.toml
Related https://github.com/stratis-storage/project/issues/699
> devicemapper v0.34.2

- .github/workflows/cargo.yml
- .github/workflows/main.yml
- .github/workflows/nightly.yml
Related: stratis-storage/project#700
> github actions: update recommended Rust to 1.77.2

- Cargo.toml
- src/core/dm_ioctl.rs
- src/core/dm_udev_sync.rs
- src/lib.rs
Related https://github.com/stratis-storage/project/issues/698
> Use once_cell instead of lazy_static for lazy statics

- src/core/dm_udev_sync.rs
Related stratis-storage/project#712
> Fix unwrap-or-default lint

- devicemapper-rs-sys/Cargo.toml
Related: stratis-storage/project#716
> Change deprecated default_features to default-features

- Cargo.toml
- src/lib.rs
Related: stratis-storage/project#720
> Fix clippy lints for Rust 1.80

- src/lib.rs
Related https://github.com/stratis-storage/project/issues/597
> Expose the message ioctl

- src/core/dm.rs
Related: stratis-storage/project#727
> dm.rs: Fix byte_char_slices lint

- .github/workflows/nightly.yml
Related https://github.com/stratis-storage/project/issues/731
> Run semantic version checks nightly

- src/core/types.rs
Related: stratis-storage/project#740
> Fix Rust 1.83 clippy errors

- .github/workflows/cargo.yml
- .github/workflows/nightly.yml
Related https://github.com/stratis-storage/project/issues/739
> Increase lowest Fedora version to f40

- .github/workflows/cargo.yml
- .github/workflows/main.yml
- .github/workflows/nightly.yml
Related: stratis-storage/project#747
> github actions: update recommended Rust to 1.84.0

- src/core/dm_udev_sync.rs
Related https://github.com/stratis-storage/project/issues/753
> clippy 1.85.0 fixes

- src/lineardev.rs
Related https://github.com/stratis-storage/project/issues/763
> Fix Rust 1.86.0 warnings and errors

- devicemapper-rs-sys/Cargo.toml
- devicemapper-rs-sys/build.rs
Related https://github.com/stratis-storage/project/issues/770
> devicemapper-rs-sys: Increase bindgen dependency lower bound to 0.71.0

- .github/workflows/cargo.yml
- .github/workflows/nightly.yml
Related https://github.com/stratis-storage/project/issues/768
> Drop f40 from Fedora version comparisons

- devicemapper-rs-sys/Cargo.toml
Related https://github.com/stratis-storage/project/issues/773
> Allow default features for bindgen dependency

- .packit.yaml
Related https://github.com/stratis-storage/project/issues/780
> Add Packit configuration for COPR builds

- .github/workflows/cargo.yml
- .github/workflows/main.yml
- .github/workflows/nightly.yml
Related https://github.com/stratis-storage/project/issues/786
> github actions: Update recommended Rust to 1.88.0

- Makefile
- src/cachedev.rs
- src/lineardev.rs
- src/thindev.rs
- src/thinpooldev.rs
> Protect format specifications erroneously interpreted as HTML tags

- .packit.yaml
Related https://github.com/stratis-storage/project/issues/794
> Set preserve_project to True for commit
