stratis-storage/devicemapper-rs

.travis.yml, Cargo.toml, src/lib.rs
- Make clippy optional; use `--features clippy` to enable it.
- Remove serialization from `Device`, and now serde isn't needed.
- Test stable, beta, and nightly in Travis CI.
- Bump semver due to the removed serialization.
Signed-off-by: Josh Stone <jistone@redhat.com>
=> Let devicemapper work on stable rust

src/lib.rs
Required for Device to be a key in a HashMap or HashSet.
=> Make Device hashable

.gitignore, Cargo.toml, src/consts.rs, src/lib.rs, src/types.rs
As part of the Stratis project Sectors, Bytes and DataBlocks structs were implemented.  These
base structs are useful for more than just Stratis.  Moving the structs to a lower level
inside devicemapper-rs will allow higher level applications  a consistent way to represent these 
fundamental types when interacting with DM.
=> Move Sectors, Bytes and DataBlocks into devicemapper-rs

src/types.rs
Since warn(missing_docs) is on, missing docstrings generate warnings.
=> Add missing docstrings for Sectors and DataBlocks

Cargo.toml, src/consts.rs, src/lib.rs, src/lineardev.rs, src/result.rs, src/segment.rs, src/util.rs
Move LinearDev from Stratis to devicemapper-rs.
Updated LinearDev::new() to take a vector of struct Segment.
Changed LinearDev functions to return DmResult
Moved wait_for_dm to DM.
Use DM::wait_for_dm() for lineardev.
Misc:
Moved IEC constants 
Added logging for debug!() used in LinearDev
=> move LinearDev to DM, add logging, move IEC constants

src/lib.rs, src/lineardev.rs, src/thindev.rs, src/thinpooldev.rs
Move thindev and thinpool from Stratis to devicemapper-rs
Minor adjustments to the use statements to match style guide
Added comments where required due to compiler warnings if not supplied
Changed fn path() to devnode() in thindev and thinpool
=> Move thindev and thinpool from Stratis to devicemapper-rs

src/segment.rs, src/thindev.rs
ThinDev::new should take a reference to the ThinPoolDev
Change Segment::new() to take Sectors rather than u64
=> ThinDev::new should take a reference to the ThinPoolDev

src/thinpooldev.rs
Instead, have it return the two members of the tuple. (Basically there
is a layer here we don't need.)
=> Do not make ThinPoolStatus contain a single tuple

src/lib.rs
These put DM and Device in the toplevel namespace so they can be used more
easily.
=> Add pub use declarations for DM and Device

src/types.rs
This is handy for adding up lengths of Segments.
newtype-derive could do this but doesn't yet, see https://github.com/DanielKeep/rust-custom-derive/pull/28
=> Implement iter::Sum for Sectors and Bytes

src/lineardev.rs, src/thinpooldev.rs
This function re-creates a previously-existing thinpool. The primary
difference between this and ThinPoolDev::new is that it calls thin_check
to verify metadata is in a good state before proceeding.
=> Add ThinPoolDev::setup

src/lineardev.rs
This saves clients needing to convert a [Segment] into a [&Segment].
=> Change LinearDev::new block_devs arg to take &[Segment]

Makefile, src/dm.rs, src/dm_ioctl.rs, src/thindev.rs, src/thinpooldev.rs
Update the code using rustfmt 0.8.3 as needed
Update the Makefile to include a format check as part of CI
Allow for 110 character line length.  The default is 100.  The code had a pointer to a long
URL.  I think allowing 110 is better than removing the comment.
=> Updates for rustfmt 0.8.3

src/lineardev.rs, src/segment.rs, src/thindev.rs
This method extends the thin volume's logical size by the number of
sectors given.
Since this involves reloading the device's table after initialization, it
was necessary to remember the associated thinpool's dstr so we could
properly reload its table. Modifying ThinDev::dm_table args was also
needed.
=> Add ThinDev::extend()

src/thindev.rs
stratisd also needs to get the thin device's size in sectors, since that's
how it saves it in metadata (at least for right now).
It also needs the thin id, for the same reason.
=> Add methods to get size as sectors and the thin id from a ThinDev

src/thindev.rs
Sectors and Bytes are differently interconvertible by means of the
methods bytes() and sectors(). sectors() has been carefully defined
to do something sensible when the value is not a whole number of sectors.
If thindev size will always be in granularity of sectors, then it is
reasonable for the unique size() method to return Sectors.
On the other hand, if thindev size will not always be in granularity of
sectors, then it would be best to have the unique size() method return
Bytes.
This commit assumes that the thindev size will always in granularity of
sectors.
=> Avoid redundannt methods

.gitignore
So they don't get accidentally included in commits.
=> Be nice to vi users by ignoring .swp files as well as .swo files

Cargo.toml, src/device.rs, src/lib.rs, src/segment.rs
Stratis would like to store and retrieve information encoded
as Segments. Do the same for Device, since Segment uses it.
=> Make Segment implement Serialize and Deserialize

src/dm.rs
See https://www.spinics.net/lists/stable/msg170390.html and 4617f564c in
the Linux kernel repo.
We were assuming hdr.data_size was always greater or equal to
hdr.data_start, but this is no longer the case.
This kernel change is also widely backported to previous kernel versions'
stable branches.
fixes #50
=> Adapt for change in 4.12+ kernels

src/lineardev.rs
This is consistent with what ThinDev::size() does, and is truer to the fact that
almost everything device-mapper-related is expressed in sectors.
=> lineardev: Change size() to return Sectors

src/result.rs, src/thinpooldev.rs
Clients need to distinguish if thin_check is the cause of the failure, so
that they may handle it, such as by running thin_repair.
=> Add CheckFailed to Error enum

src/types.rs
Sometimes, we want to explicitly check if the values will overflow on
addition.
=> Add a checked_add() method for Bytes and Sectors

src/dm.rs
It is already that type, now use the name TargetLine for that type.
=> Change return type argument to TargetLine

src/thindev.rs
It's the same as new, except don't send the create_thin message.
=> add ThinDev::setup

Makefile
It is convenient to run basic unit tests and non-running doc tests
on one's own system.
On the CI, continue to run all tests as root.
This is a somewhat temporary expedient. If more tests that require root
are added, it may pay to better distinguish between the different types of
tests.
=> Add a Makefile target that runs only non-root tests

src/lib.rs, src/thindev.rs
The type can be amended or improved later, but at least it gives something
close to the maximally random number now.
=> Since thindev ids are inconveniently special, give them a type

Cargo.toml, src/lib.rs
It hasn't figured in CI for quite a while.
=> Get rid of all allusions to clippy

src/dm.rs, src/thinpooldev.rs
extend() function for ThinPoolDev is needed to allow users to extend the segments allocated
to the meta and data backing devices.
=> Add extend to thinpooldev

.travis.yml, Cargo.toml, Makefile, src/consts.rs, src/dm.rs, src/lib.rs, src/lineardev.rs, src/thindev.rs, src/thinpooldev.rs
Break out the various targets into separate runs and add clippy target
back in as an allowed failure.
=> Improve CI

src/types.rs
They already derive Sub, SubAssign is really just a convenience.
=> Have Bytes, Sectors, DataBlocks derive SubAssign

src/deviceinfo.rs, src/dm.rs, src/lineardev.rs
Give it a constructor and make hdr private.
Box it in LinearDev to make LinearDev cost less to move.
=> Small fixes having to do with DeviceInfo

src/thindev.rs
This function tears down the DM device, but also messages thinpool to free
up resources associated with the thindev.
=> Add ThinDev::destroy()

src/dm.rs
The ioctl that it wraps returns an error if the names are the same,
but it is much better if we don't.
=> Make device_rename idempotent

src/types.rs
Everything that can be macroized for Sectors, Bytes, DataBlocks, has
been macroized.
Note that at some point, if DataBlocks is rewritten, how it is serialized
may change and the current macro may not work any more.
=> Use macros to implement serialization and deserialization

.travis.yml, src/device.rs, src/dm.rs, src/lineardev.rs, src/thindev.rs, src/thinpooldev.rs
This change eliminates the majority of the outstanding clippy errors as a side-effect.
So this PR follows up the devnode changes by eliminating all clippy errors and making clippy mandatory.
=> Do not scan /proc/partitions for device node

src/lib.rs, src/thinpooldev.rs, src/types.rs
Use a MetaBlocks type for tracking the meta data device utilization.
dm.table_status() for a thin pool returns the meta device usage in blocks. The
block size for a meta is a constant 8 sectors.  The MetaBlocks type
wraps these sizes.
=> define a type for MetaBlocks to be used for tracking thin-meta use

src/dm.rs
It has remained unimplemented since Aug, 2015, when it was first introduced
along with a bunch of other unimplemented methods, all of which have since
been implemented.
=> Drop an unimplemented method

src/dm.rs
This reverts commit b54dcd1caa353b5510a980034761425a11926aae.
It only works properly for a name, but "name" might be a UUID.
=> Revert "Make device_rename idempotent"

src/device.rs, src/lineardev.rs, src/thindev.rs, src/thinpooldev.rs
This reverts commit 5c217326dffccffe1a955d692c27111b3aab5409.
The updates to devnode() caused some troubles with Stratis.  Reverting
the commit for now until we can work through the issues.
=> Revert "Do not scan /proc/partitions for device node"

src/types.rs
Leave out sum(), because it also requires implementing Default,
which might not be obvious for DataBlocks.
=> Implement multiplication and serde on all *Blocks types

Makefile
It really just gets in the way.
=> Get rid of verbose flag for clippy task

src/dm.rs, src/lib.rs, src/lineardev.rs, src/shared.rs, src/thindev.rs, src/thinpooldev.rs
Do not fail, if when setting up or creating a DM device, it is already registered with the kernel.
=> Make new() and setup() methods approach idempotency

src/thindev.rs
New clippy version 0.148 finds new errors.
=> Fix clippy error unreadable_literal

.travis.yml
This removes the `sudo: required` from all builds except the `sudo_test` one, which should improve the CI boot time. See https://docs.travis-ci.com/user/reference/precise/#Virtualization-environments for more information.
=> Travis: Use container infrastructure

.travis.yml
It is now the default on Travis.
=> No longer specify trusty distribution

Cargo.toml, Makefile, src/dm.rs, src/lib.rs, src/lineardev.rs, src/loopbacked.rs
This takes the loopbacked testing infrastructure from stratisd and puts it in the src directory. Using this arrangement, it is possible to run tests using external devices using the Rust unit test framework. The PR also add a few more dm tests that don't require the framework, and a bunch of lineardev unit tests that mostly make use of the framework.
I believe that it would be straightforward to also port the "real" testing framework from stratisd, but I have not done so.
=> Add a testing infrastructure and some more tests

src/deviceinfo.rs, src/dm.rs, src/lib.rs, src/lineardev.rs, src/shared.rs, src/thindev.rs, src/thinpooldev.rs
This PR is supposed to help clarify the use of various things for identifying devices.
* It rewrites DevId substantially.
* It documents that a devicemapper uuid is not an ISO standard UUID.
* It changes a confusing parameter name, "name", to "id", which is a bit better.
* ```DM::device_rename()``` does not allow specifying the device by uuid either when renaming or when setting a uuid.
* Has LinearDev::set_name() return the DeviceInfo from device_status() call.
* Makes LinearDev::set_name() idempotent.
* Adds a bunch of tests.
Resolves #90.
Resolves #92.
=> Work on devicemapper identifiers

src/segment.rs
Members of Segment are cloneable. This would also be generally useful.
=> Derive Clone for Segment

src/dm.rs, src/lineardev.rs, src/loopbacked.rs, src/thinpooldev.rs
Devicemapper stands on its own. There are a few harmless mentions of
Stratis in the code and test strings, but let's try to avoid these just on
principle.
Take the opportunity to describe in more detail how we can be sure the DM
kernel interface won't change under us and cause a crash.
=> Tidy some mentions of Stratis in devicemapper-rs

src/deviceinfo.rs, src/dm.rs, src/lineardev.rs, src/shared.rs, src/thindev.rs, src/thinpooldev.rs
A little poking around to see if we could implement ToOwned for DmName has led me to the conclusion that DmName should be an unsized type, wrapping `str` not `&str`.
This PR undoes some changes in #141. In looking at the code more I gained some insights that would have been REALLY good to bring up in the earlier PR's review. I'm sorry for not doing so earlier and noticing before it was merged (and tagged).
=> Change DmName/DmUuid to be unsized

src/device.rs, src/deviceinfo.rs, src/dm.rs, src/lib.rs, src/lineardev.rs, src/loopbacked.rs, src/shared.rs, src/shared_macros.rs, src/thindev.rs, src/thinpooldev.rs, src/util.rs
A devicemapper device implements DMDevice and delegates some actions to a transitively contained Device object.
=> Distinguish between a devicemapper device and an arbitrary device

src/lineardev.rs, src/shared.rs, src/thindev.rs, src/thinpooldev.rs
In ThinDev and ThinPoolDev::setup(), we create and load a device if it
doesn't exist. However, if table load fails (e.g. if attempting to load
a thindev whose thin_id doesn't exist) then the newly created device is
left dangling. In this case, make sure to not leave the created-but-not-
loaded table as we return with the Err.
=> Clean up DM device if table load fails

Makefile
This assumes that cargo-tree has been installed in the same way as
cargo-fmt.
=> Run cargo-tree from Makefile using "make tree"

src/lineardev.rs, src/shared.rs, src/shared_macros.rs, src/thindev.rs, src/thinpooldev.rs
Device is copy, and a better choice as an identifier when not passing the
entire DmDevice as an argument.
ThinDev now stores its thinpooldev as a Device, not a String.
The need for a special type for Dstr goes away entirely, since Device
implements Display in the necessary format.
=> Require device() instead of dstr() in DmDevice

src/loopbacked.rs
This code is only used in tests, and it is not dead there.
=> Get rid of some unnecessary allows

src/lineardev.rs, src/shared.rs, src/thindev.rs, src/thinpooldev.rs
This was actually a bit of a bug, because it would be bad news if the
name and the id specified different devices.
=> Remove redundant parameter from device_create

src/lineardev.rs, src/thinpooldev.rs
There is no other method in LinearDev, ThinDev, ThinPoolDev where the
context is instantiated within the method. If the context is required,
it is always passed as a parameter. This makes it the same for this method.
=> Pass devicemapper context to LinearDev::extend()

src/thindev.rs
We presume that if the table reload fails, the kernel still considers
size of thindev to be old size, so stratisd should, too.
=> Update thindev's size only after table_reload succeeds

src/thindev.rs
It's just being inspected, not changed. This change should ease error
handling. Change "status" to "table" where the value really is a table.
=> Do not make table mutable unnecessarily

src/lineardev.rs, src/thinpooldev.rs
These are really just representations of data, not things that should be
claimed. The segments are all cloneable.
Also, it should make error-chain easier, since the segments no longer
need to be moved in the same way.
=> Pass Vec<Segment> as &[Segment]

src/thindev.rs
Taking a snapshot of a ThinDev creates a new ThinDev that is no different
than any other thin provisioned device.
Documentation for snapshots can be found at:
https://www.kernel.org/doc/Documentation/device-mapper/thin-provisioning.txt
See section i) Creating an internal snapshot.
=> implement snapshot for a thindev

src/lineardev.rs
Only one line is not enough for a LinearDev as its tables are, in general,
more than one line.
=> Extend a test with a slightly more interesting table

src/dm.rs, src/lineardev.rs, src/shared.rs, src/thindev.rs, src/thinpooldev.rs
Add ability to set optional UUID parameter in ```new()``` and ```setup()``` methods.
Makes placement of DM parameter consistent in these methods with other methods.
Fixes a minor bug in ```device_match()```.
Supercedes #161 .
=> Add optional UUID parameter to setup() and new() methods

src/lib.rs, src/thindev.rs, src/thindevid.rs
For better encapsulation and testing; it should make other refactorings
easier.
=> Refactor ThinDevId impl into a separate module

Cargo.toml, src/device.rs, src/deviceinfo.rs, src/dm.rs
We can't assume which bits in a libc::dev_t are major and which are minor.
This is especially true since the default is to use an intermingled
pattern that allows for >256 major and minor, but keeps the layout the same
as the old 16 bit dev_t if both values are less than 256.
Also properly convert to/from the kernel's dev_t encoding. Even though
DM's ioctl struct has a 64 bit field for this, it uses the kernel's
"huge" encoding, which is only 32 bits. Therefore it's possible to have
a valid Device that cannot be expressed to the kernel. But, this field
isn't currently ever set right now. If we ever want to specify DM devices
by maj:min then we'd need to use to_kdev_t().
fixes #147
=> device: Convert to/from dev_t and kdev_t

src/thindev.rs, src/thinpooldev.rs
The test is really more appropriate in devicemapper than stratisd, as it tests
only devicemapper functionality.
The minimal thinpool has to be made slightly larger, so that an xfs filesystem can be made on a thindevice in the pool.
=> Transfer a test from stratisd to devicemapper

src/deviceinfo.rs, src/dm.rs, src/lib.rs, src/lineardev.rs, src/shared.rs, src/thindev.rs, src/thinpooldev.rs, src/types.rs
it would have been nice to use an enum, but the list of target names is a bit open-ended.
The nice part is that now the first error that can result from a bogus target name in the table passed as an argument goes away. Instead, the check is done at the point where the target name is created.
=> Use a dedicated type for targets

src/dm.rs
It's the default, so clippy would prefer us to leave it out.
=> Omit 'static lifetime from DM_CTL_PATH type

src/dm.rs
It is fairly clear why empty flags are passed, so the comment is not
necessary.
=> Get rid of frequently repeated comment

src/dm.rs, src/shared.rs, src/thindev.rs, src/thinpooldev.rs
Introduce a generic way of messaging a device. This should be just as useful for messaging cache devs as for messaging thinpool devs.
=> Some work on messages

src/thinpooldev.rs
The devices that went into the failed new() command need to be cleaned up.
=> Clean up after an existing thinpool test

src/lib.rs, src/thinpooldev.rs, src/types.rs
Some minor tweaks to ThinPoolDev implementation and related.
These come up since CacheDev is more similar to ThinPoolDev than any other device implemented so far.
=> More tweaks about thinpool devices

src/dm.rs
targ.next (next_off) apparently counts from the start of the entire buffer,
not the end of the previous target entry! This only bites us when a device has 3
or more entries.
=> Fix bug when parsing a device with 3 or more tables

src/cachedev.rs, src/device.rs, src/dm.rs, src/lib.rs, src/lineardev.rs, src/loopbacked.rs, src/shared.rs, src/shared_macros.rs, src/thindev.rs, src/thindevid.rs, src/thinpooldev.rs, src/types.rs
This PR addresses the problem that we check equality of two devices by checking equivalence of tables, but that we do this by checking string equality of the string representing their device-specific parameters. This PR introduces a notion of equality embedded in a type called TargetParams and allows this notion of equality, implemented in the method ```equivalent_tables()``` to be modified for each type of device. It also introduces a modification to CacheDev's notion of equality to omit the replacement policy from its equivalence check. There are almost certainly other values stored in tables that should also be omitted in an equality check, but this PR leaves that for further work when a better understanding of the meaning and importance of these values has been gained.
This PR has …
=> Improve implementation and use of TargetLine type

Cargo.toml, src/lib.rs, src/lineardev.rs
I believe that it has served its purpose as a development aid, and it
would be unlikely to be all that helpful for customer debugging.
When there is a failure, we would be better served by packaging that
information up in the error returned.
Get rid of log, env_logger requirements. They can be re-added w/ a small
amount of effort as necessary.
Resolves: #16.
=> Omit debug! in LinearDev::dm_table

src/cachedev.rs, src/dm.rs, src/lib.rs, src/lineardev.rs, src/shared.rs, src/thindev.rs, src/thinpooldev.rs, src/types.rs
This takes the use of TargetLine and TargetParams, in terms of which TargetLine is defined out of core methods and confines its use to the outer layer.
TargetLine can only be used in one place in the core, ```DM::table_load```, and the only benefit to this use is using names instead of indices to access values. One could go further, and parameterize ```DM::table_load``` on the TargetParams, but then you get as many copies of this method as there are types of device, thin, thinpool, etc., all for the benefit of calling ```to_string()``` in exactly one place in the method. I'm pretty sure that is not enough benefit.
=> Do not use TargetLine in devicemapper core methods

src/cachedev.rs, src/lineardev.rs, src/shared.rs, src/thindev.rs, src/thinpooldev.rs
This changes the name of internal ```dm_table``` function, and implements ```equivalent_tables``` for all devices.
Resolves: #232.
=> Be more explicit about default values in tables

.travis.yml, Makefile
Use rustup to set the version of rustfmt so that it is recognized.
Modify the existing fmt target so that it just reformats text inline.
This seems the handier thing for regular command-line users.
=> Make a special make target for fmt test on Travis

Cargo.toml, src/device.rs, src/thindev.rs
This requires an explicitly higher version of backtrace and of libc.
Resolves: #263.
=> Update nix to v0.10.0

src/cachedev.rs
This is a bug fix. cache and origin order were swapped in CacheDev::setup.
=> Pass arguments to CacheDev::gen_default_table in proper order

src/dm.rs
When it fails, the failure will be more informative.
=> Add a more precise condition in list_devices test

src/loopbacked.rs
See: https://doc.rust-lang.org/std/io/enum.SeekFrom.html
=> SeekFrom::Start() takes bytes as a parameter (not Sectors)

src/thinpooldev.rs
If the pool is out of space, we want the pool to return errors to XFS as soon as possible.
=> Change default for pool to error_if_no_space

.travis.yml
A new version has been released, which we hope will work.
=> No longer allow failures for clippy

.travis.yml
It has become too flaky to be allowed to gate a PR.
=> Make clippy an allowed failure on Travis CI

src/cachedev.rs, src/dm.rs, src/dm_flags.rs, src/dm_options.rs, src/lib.rs, src/lineardev.rs, src/shared.rs, src/test_lib.rs, src/thindev.rs, src/thinpooldev.rs
Replace pub functions which took a DmFlags with a new DmOptions which utilizes a
builder pattern.  With this change we should be able to accommodate changes to
the device mapper structure over time, especially the IOCTL structure without
requiring new function calls to be created for every affected function.
=> Add DmOptions builder

src/cachedev.rs, src/lineardev.rs, src/shared.rs, src/thindev.rs, src/thinpooldev.rs
~~Current best approach for getting existing user space udev rules
to do what we need to get Stratis to be used for root fs and for
allowing Stratis backed XFS fs mounted in fstab.  This works by
setting a cookie value when we un-suspend the newly created thin
device which is utilized for newly created FS.~~
Current best approach for getting existing user space udev rules
to do what we need.  To allow Stratis to be used for root fs and for
allowing Stratis backed XFS fs mounted in fstab.  This works by
setting a cookie value when we resume the newly created thin
device which is utilized for newly created FS.
=> Add DmOptions parameter to device_create

src/loopbacked.rs
The file.flush() is currently implemented as a no-op in Rust.
Resolves: #318.
=> replace file.flush() with file.sync_all()

Cargo.toml, src/lib.rs, src/thindev.rs
Previous PR:
#323
Introduced a cookie to get userspace to handle udev event, but
we left out the setup and snapshot code paths, so add those too.
=> Set cookie for setup and snapshot

src/types.rs
The derived Debug implementation when pretty-printed results in e.g.:
Sectors (
0
)
This changes it to:
Sectors(0)
which isn't a huge change but is worth it because these types are used
very frequently.
=> Implement Debug for Sectors, DataBlocks, Bytes, and MetaBlocks

src/errors.rs, src/test_lib.rs
We believe that the necessity has been removed by the recent error-chain
update: https://github.com/rust-lang-nursery/error-chain/issues/245
=> Remove some error-chain specific clippy allows

Makefile
Semantics of diff seems to have changed. It used to return non-zero code
if there was a difference, now it doesn't. Semantics of check seems to
be what we want for a test; it seems to behave like diff used to.
=> Use write mode check instead of diff for cargo fmt

src/cachedev.rs, src/lineardev.rs, src/shared.rs, src/thindev.rs, src/thinpooldev.rs
The problem with teardown taking self is that if it fails, we no longer
have ownership of the object. Instead, pass in a mutable reference. This
leaves the caller with the object if the teardown/destroy fails.
=> Change teardown methods to take &mut self

src/device.rs, src/dm.rs, src/errors.rs, src/thindev.rs, src/thinpooldev.rs
Due to restrictions in the standard library, using error-chain does not
allow most handy programmatic access to the elements of the chain.
Thus, it seems better to fall back on a simple type-based mechanism,
which is unfortunately more brittle but also more useful.
Make some description fields more descriptive.
Do not bother to remove error-chaining from test infrastructure, it is
not necessary to have programmatic access to it in the same way as to
a part of the actual library.
=> Use primitive type-based chaining mechanism

src/dm.rs, src/errors.rs
If it is, then that length can not be specified in the hdr and the ioctl
can not work properly.
=> Return an error if buffer size is larger than u32::MAX

src/thinpooldev.rs
Since we're passing new_table to table_load, that's the one we need
to set the low water mark for.
self.table gets set to new_table if the load succeeds.
=> Fix ThinPoolDev::set_low_water_mark()

src/thindev.rs
They are almost certainly harmless, but they're not exactly correct either.
=> Get rid of stratis mentions in devicemapper

.travis.yml
clippy wants scope modifiers for allow directives, but my current compiler
won't deal with them. We need to persuade clippy to accept directives
without scope modifiers or compiler to ignore directives with modifiers,
and we haven't figured out how to do that yet.
So, since snapshot is coming up soon, not gating PRs on clippy correctness
seems like a good idea.
I couldn't find any issue about this at clippy repository.
=> Make clippy task an allowed failure

.travis.yml, src/cachedev.rs, src/device.rs, src/dm.rs, src/dm_flags.rs, src/lib.rs, src/lineardev.rs, src/loopbacked.rs, src/test_lib.rs, src/thindev.rs, src/thinpooldev.rs, src/types.rs
Required for newer versions of Rust/clippy.
=> Make clippy a mandatory test once more

src/thinpooldev.rs
Resolves: https://github.com/stratis-storage/stratisd/issues/1374.
See #400, for some remarks on the correct way to go about it.
=> Make no_discard_passdown the default for thin pools

.travis.yml, Makefile
* Add allowed failure beta target
* Pin clippy compiler version
* Use fast_finish flag
* Use Travis config to specify minimum supported version
* Comment all Travis task
* Use Travis config to pin rustfmt version
=> Bring devicemapper CI in line with stratisd CI

src/dm.rs
trim_right is deprecated in 1.33.0.
trim_end just transitively calls trim_right in current code base, so there
is no semantic change.
=> Replace trim_right with trim_end

src/thinpooldev.rs
Since my doc fix commit cc3ff0af19499f0aaa587f42d3091b4dff49208f
was merged in the kernel the items are listed in the correct order, so
there is nothing to explain.
=> Remove note about discrepancy between devicemapper code and kernel docs

src/test_lib.rs
error-chain is in maintenance mode and may not fix the problem.
In any case, we would like to move away from error chain.
=> Allow deprecated usage in the code produced by an error-chain macro

.travis.yml
Compilation does not proceed very far at all on tests if using the build
target, but we do want to check tests.
=> Build both source and tests on lowest supported compiler

src/cachedev.rs, src/shared.rs, src/thindev.rs, src/thinpooldev.rs
The objects of this PR are:
* Better encapsulation.
* To be better prepared for a possible future refactoring that eliminates the concept of distinct kinds of devices entirely.
* To eliminate some needless boiler plate.
* To get rid of the last risky assertion involved in reading a single status line.
* To get rid of some obsoleted comments.
* To parse one last thinpool status value, held metadata root.
This is a continuation of #387 and really resolves #221. It supercedes #410.
=> Tidy up *dev status methods more (final)

src/shared.rs
First we must dereference the value, because it is a reference to a
DmNameBuf. Then we dereference it again, so that the deref can be invoked.
Then, we make it a reference again so that its type matches the type
of the value on RHS of the equal sign.
=> Get rid of a TODO

src/core/dm.rs
To be on the safe side. Also, it looks tidier because it matches the code
block following.
=> Trim the end of the target type string

src/range_macros.rs
This was missing from commit f4f2fdd53940d94431c5022798360b4ea7.
=> Use #[cfg(test)] for range_macros tests

.travis.yml, Makefile
This is a convenience rather than a check, although it may be moved up to a check at some time. It is the case that cargo-expand takes longer than any other of the Travis tasks, however, the configuration file is set up so that the cumulative result is reported as soon as the required tasks are done, so this should not slow work at all.
=> Show expanded macros on Travis

Cargo.toml, src/lib.rs, src/range_macros.rs, src/units.rs
-Wrote macros to implement the traits Add, Sub, AddAssign, SubAssign, Deref, From
-Replaced calls to Newtype macros with these new macros
-Removed the macro_attr and newtype_derive dependencies from definition of units
-Build size reduced by 2.36% (was 9241466, is now 9023322)
=> Removed the macro_attr and newtype_derive dependencies from definition of units

src/core/types.rs, src/loopbacked.rs
Due to a recent Rust update, several unused documentation comments were causing the beta task to fail. In this PR, I turned those documentation comments into regular comments, so that all Travis CI tasks succeed.
=> Turned unused doc comments into regular comments

Cargo.toml, Makefile, src/core/dm.rs, src/lib.rs, src/range_macros.rs, src/testing/loopbacked.rs
Please consult edition 2018 blog entry for an overview of changes:
https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-rust-2018.html.
This PR omits enforcing two rust-2018-idioms: elided-lifetime-in-paths and explicit-outlives-requirements. Both are lints which allow the programmer to elide certain lifetime annotations. At this time, these elisions seem to me not to increase the clarity of the code, so I see no reason to enforce them.
=> Move to edition 2018

src/cachedev.rs, src/shared.rs, src/shared_macros.rs, src/thindev.rs, src/thinpooldev.rs
The two contributions of this PR are:
* It eliminates three assertions that aren't logically necessary.
* It abstracts what is one action into a single method.
Related: https://github.com/stratis-storage/project/issues/29
=> Abstract getting unique status result into a single method

Cargo.toml
This is needed to fix breaking changes in libc on arm and s390x.
See: https://github.com/nix-rust/nix/pull/1055
=> Update nix to 0.14

.travis.yml, src/cachedev.rs, src/thinpooldev.rs
Related: https://github.com/stratis-storage/project/issues/46.
=> Increase recommended development rust toolchain verson to 1.35

.travis.yml
Related: https://github.com/stratis-storage/project/issues/47.
=> Increase lowest supported rust toolchain to 1.35

src/cachedev.rs, src/core/dm.rs, src/lineardev.rs, src/thindev.rs, src/thindevid.rs
Changes:
- Replace assert!(<expr>.is_ok()) with assert_matches!(<expr>, Ok(_))
- Replace assert!(<expr>.is_err()) with assert_matches!(<expr>, Err(_))
Additional information:
- The purpose of these modifications is to provide more useful information
upon assertion failure.
=> Replace assert! with assert_matches!

.travis.yml
Related: https://github.com/stratis-storage/project/issues/88.
=> Increase lowest supported Rust toolchain to 1.37

.travis.yml
Related: stratis-storage/project#112.
=> Increase lowest supported Rust toolchain to 1.38

src/testing/mod.rs, src/testing/test_lib.rs
This PR tries to improve encapsulation by making test_lib private in the testing submodule and removing one publicity modifier that becomes not-useful with the preceding change.
=> Do not make test_lib public outside the testing module

src/core/types.rs, src/id_macros.rs, src/range_macros.rs, src/shared.rs, src/shared_macros.rs, src/units.rs
Resolves: #522
Supercedes: #523
=> Use fully qualified name for all macro non-prelude types

.travis.yml
Related: https://github.com/stratis-storage/project/issues/146.
=> Increase lowest supported Rust toolchain to 1.41

.travis.yml, src/testing/loopbacked.rs
Signed-off-by: Bryan Gurney <bgurney@redhat.com>
=> beta clippy: remove unneeded unit return type

.travis.yml
This reverts commit 3e5d4852d738b922cca99dddfb314ae03dfcb0a8.
=> Revert "Temporarily allow beta clippy Travis task to fail"

src/thindev.rs
Closes: stratis-storage/project#220
=> test_basic: use assert_matches to check for ThinStatus non-failure

src/range_macros.rs, src/testing/loopbacked.rs, src/testing/test_lib.rs, src/units.rs
=> Migrate Bytes to u128 internally

src/core/device.rs, src/core/dm.rs
The android target needs some minor adjustments:
* The device mapper control file is located at `/dev/device-mapper` instead of `/dev/mapper/control`
* `major` and `minor` types differ
* `ioctl op code differs in type (`i32` vs `u32`)
* The android target lacks `MetadataExt`. The `metadata` call is replaced with a plan `stat` from `nix`. The error type slightly   changed to a wrapped `nix::Error` in an `io::Error`. Not sure if this is ok or not.
=> Enable build for android targets

Cargo.toml
`bindgen` is used for generating ffi bindings from a build script. The bindgen feature to create bindings with the `bindgen` CLI is not needed and can be turned off when depending on `bindgen`. Turning off the default features reduces the number of (build) dependencies of `devicemapper-rs`.
A diff of the output of `cargo tree` with and without this patch shows the removal of `clap`, `regex` (features), `env_logger`, `log`, `which` and their dependencies:
```diff
44,64d43
<     ├── clap v2.33.3
<     │   ├── ansi_term v0.11.0
<     │   ├── atty v0.2.14
<     │   │   └── libc v0.2.94
<     │   ├── bitflags v1.2.1
<     │   ├── strsim v0.8.0
<     │   ├── textwrap v0.11.0
<     │   │   └── unicode-width v0.1.8
<     │   ├── unicode-width v0.1.8
<     │   └── vec_map v0.8.2
<     ├── …
```
=> Turn off bindgens default features and enable feature runtime

src/cachedev.rs, src/core/dm.rs, src/lineardev.rs, src/shared.rs, src/thindev.rs, src/thinpooldev.rs
When loading a verity table the device *must* be a readonly. The dm driver requires the flags for the `DM_TABLE_LOAD_CMD` ioctl to include at least `DM_READONLY` - otherwise it complains:
```
May 25 19:32:42 XXX kernel: [ 7763.805044] device-mapper: table: 254:7: verity: Device must be readonly
May 25 19:32:42 XXX kernel: [ 7763.805049] device-mapper: ioctl: error adding target to table
```
Add `core::dm::table_load_flags` that enables any user to pass `DmFlags::DM_READONLY` to the `DM_TABLE_LOAD_CMD` operation.
An Option could be to extend `table_load` with an `Option<DmFlags>`. This changes the API in a breaking way, so I decided to add `table_load_flags`. Let me know if you prefer the `Option` argument.
It's possible that other options than `DM_READONLY` are allowed for the …
=> Add flags option to table loading

src/core/dm.rs
crypt devicemapper targets pass secrets in the table_load ioctl
and should be called with DM_SECURE_DATA set. This patch makes
that flag allowed in table_load calls.
=> Add support for DM_SECURE_DATA flag in table_load

src/cachedev.rs, src/lineardev.rs, src/shared.rs, src/shared_macros.rs, src/thindev.rs, src/thinpooldev.rs
Closes #663 
Generalize ```DmDevice::suspend()``` and ```status()``` functions to take a ```DmOptions``` argument. Many other, device-specific functions invoke ```status()``` or ```suspend()``` methods, in many cases hard-coding the ```DmOptions``` argument that is passed; no effort is made here to generalize these functions as I believe that the code there may require a significant redesign.
=> Generalize DmDevice::suspend and status() functions to take a DmOptions argument

src/core/device.rs
=> Fix some build and clippy warnings caused by increasing version of libc dependency to 0.2.133

src/core/dm.rs, src/lineardev.rs, src/thinpooldev.rs
Links a few items to docs.kernel.org, which contains pretty, rendered pages that are
easier to read than the git tree soruce files.
=> Fix rustdoc warnings and improve documentation

src/core/deviceinfo.rs, src/lib.rs
Several methods return this structure but since it's not publicly exported, users can't name the type nor get documentation for it.
=> Expose DeviceInfo struct

Cargo.toml, devicemapper-rs-sys/Cargo.toml
Related https://github.com/stratis-storage/project/issues/570
=> Increase nix dependency lower bound to 0.26.0

.github/workflows/cargo.yml, .github/workflows/main.yml, Cargo.toml, devicemapper-rs-sys/build.rs, devicemapper-rs-sys/dm.h, devicemapper-rs-sys/sem.h, devicemapper-rs-sys/src/lib.rs, src/cachedev.rs, src/core/dm.rs, src/core/dm_flags.rs, src/core/dm_options.rs, src/core/dm_udev_sync.rs, src/core/errors.rs, src/core/mod.rs, src/core/sysvsem.rs, src/lib.rs, src/shared.rs, src/testing/logger.rs, src/testing/loopbacked.rs, src/testing/mod.rs, src/thindev.rs
This branch adds support for udev synchronization using SysV semaphores and the device-mapper ioctl/uevent "cookie" mechanism.
The branch adds a new sub-module, `dm_udev_sync` that wraps the low-level semaphore operations and provides an interface to `core::dm`.
All udev synchronization is carried out insde `DM::do_ioctl()`. This centralises and simplifies handling ioctl errors (which require the udev semaphore to be cleaned up before propagating the error) and minimises the changes needed to synchronize with uevents.
This branch also adds basic logging infrastructure to the crate, using the log facade and the env_logger crate: this was helpful in developing and debugging the udev interactions and may be useful for debugging other problems involving device-mapper.
=> Add udev semaphore synchronization for uevent-generating commands

src/cachedev.rs, src/lib.rs, src/thindev.rs, src/thinpooldev.rs
Related to stratis-storage/stratisd#3274
=> Make target table structs public to support easier alternate table construction

Cargo.toml
Related https://github.com/stratis-storage/project/issues/588
=> Increase env_logger dependency lower bound to 0.10.0

src/cachedev.rs, src/core/dm_options.rs, src/lineardev.rs, src/thinpooldev.rs
Pull request #774 adds support to devicemapper-rs for synchronizing with Udev events. This causes the DM_UDEV_PRIMARY_SOURCE flag to be set for all ioctl operations that generate uevents. Previously this flag was only set for `ThinDev` devices (i.e. the top-level thin leaf devices allocated from a thin pool).
This has the unwanted side effect of making other internal device types visible in the Udev database which has consequences for other components (e.g. Udisks).
Restore the previous behaviour of only exposing the `ThinDev` devices by introducing a new `DmOptions::private()` helper to set appropariate DM_UDEV_* flags controlling the visibility of other device types.
=> Make internal devices private by default

src/shared.rs, src/thindev.rs
Related https://github.com/stratis-storage/stratisd/issues/3301
=> Make CacheDev, LinearDev and ThinPoolDev private on resume()

CHANGES.txt, Cargo.toml
Related https://github.com/stratis-storage/project/issues/673
=> devicemapper v0.34.0

src/core/dm.rs
Commit 66e1fdf2 added logging to the DM module using the debug! macro.
In practice these messages can be very noisy, especially for e.g. in the Stratis test suite (which calls the status() method on thin pool devices). This leads to lots of messages like the following:
[2023-11-06T16:01:05Z DEBUG devicemapper::core::dm] Retrieving table status for stratis-1-private-50db9929d265403b820bb155c8f5ae89-thinpool-pool
Running the Stratis test suite results in hundreds of these messages being logged at debug level.
Downgrade the logging calls in the DM module from debug! to trace! to quiet this down.
=> Downgrade DM debugging messages to trace level

.github/workflows/cargo.yml, .github/workflows/main.yml, .github/workflows/nightly.yml, .github/workflows/weekly.yml
Related: stratis-storage/project#684
=> Use checkout@v4

Cargo.toml, Makefile, devicemapper-rs-sys/Cargo.toml
Related https://github.com/stratis-storage/project/issues/721
=> Use Cargo.toml to specify lint policy

devicemapper-rs-sys/Cargo.toml, devicemapper-rs-sys/build.rs
This  MR is a follow up from: https://github.com/stratis-storage/libblkid-rs/pull/171
The minimum version chose is from 2018, and I tested I could build against said version.
=> build.rs: Add support for finding header paths with pkg-config

devicemapper-rs-sys/build.rs
Related to #965 
I'll be putting up another PR for the other libraries that use pkg-config.
=> Disable cargo metadata in pkg-config probe

Cargo.toml, src/testing/test_lib.rs
=> Use procfs instead of libmount to read mountinfo
